module.exports = {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'type-enum': [
      2,
      'always',
      [
        'build',
        'chore',
        'ci',
        'docs',
        'feat',
        'fix',
        'perf',
        'refactor',
        'revert',
        'style',
        'test',
        'enhance',
      ],
    ],
    'scope-enum': [
      2,
      'always',
      [
        'apps/web',
        'packages/api',
        'packages/state',
        'packages/ui',
        'packages/hooks',
        'packages/infrastructure',
        'packages/types',
        'packages/utils',
        'packages/math',
        'packages/persistence',
        'packages/auth',
        'packages/eslint-config',
        'packages/typescript-config',
        'root',
      ],
    ],
    'scope-empty': [0, 'never'],
    'subject-case': [2, 'always', 'lower-case'],
    'subject-empty': [2, 'never'],
    'subject-full-stop': [2, 'never', '.'],
    'header-max-length': [2, 'always', 72],
  },
};